### PR TITLE
Add GitHub Action - Markdown link check

### PR DESCRIPTION
**Pull request by bergjohan**
Hi, I saw @claremacrae  already made some progress on automated link checking, but I decided to give it a go.

I found https://github.com/gaurav-nelson/github-action-markdown-link-check which looked pretty nice.

I created an action that runs on push for master and scheduled every monday at 9 am by cron. I used `use-quiet-mode` to to only show errors in output and `use-verbose-mode` to show detailed HTTP status for checked links.

I tested it on my fork, and it seemed to work as expected.

To test the scheduled cron, you could change it to run every 5 minutes by changing the `cron` field to `"*/5 * * * *"`, I believe that's the minimum.

Ref: #28

### CODE REVIEW

**Comment by bergjohan** [comment]
Here's a screenshot from one of the test runs:

test

**Comment by claremacrae** [comment]
This is fantastic - I didn’t know there was a reusable action to do the work already…

Do you know if it’s possible to change the trigger to only happen when run by the main account?

The reason I ask is that on another repo where I set up CI builds, the cron jobs happen on all forks too… And as more people fork this repo over time, to issue a PR and then never update their fork (until maybe the next PR)….

- I think the cron job will be checking an increasingly out-of-date set of links, so they may get failure notifications every Monday, which they won’t want to fix…
- An gradually increasing number of forks will all be checking links at 9am on a Monday, which could eventually get a bit onerous on the sites being checked.

(I know that if I ran the previously link-checking mechanism several times on the same day, github eventually started blocking requests from me, so they have some kind of rate-limiting)

**Comment by bergjohan** [comment]
If I understand correctly, it should be a project setting that's disabled by default.

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

> To help prevent this, workflows on pull requests to public repositories from some outside contributors will not run automatically, and might need to be approved first. By default, all first-time contributors require approval to run workflows. However, you can configure this behavior for a repository, organization, or enterprise.

When I tested the action on my fork, I had to enable it on the action tab before being able to get it to run.

**Comment by claremacrae** [comment]
Thanks.

The thing I saw happens without any PRs being created. I think that page is covering something different, that is, whether the PR triggers a CI action in the parent repo (as someone could include something malicious in the PR code, causing it be run in the parent repo as soon as the PR is created…)

I’m concerned about CIs running in the fork repos, due to cron.

An example is this:

The Python cron CI for approval tests has started failing because of a change made to another repo (conan-center-index)…
https://github.com/approvals/ApprovalTests.cpp/actions?query=branch%3Amaster+workflow%3Apython-tests

At the same time, the same cron CI build in my fork of approval tests also started failing…
https://github.com/claremacrae/ApprovalTests.cpp/actions?query=branch%3Amaster+workflow%3Apython-tests

**Comment by claremacrae** [comment]
> When I tested the action on my fork, I had to enable it on the action tab before being able to get it to run.

Oh, I think this is the key bit… I wonder if I had done this on my fork of Approval Tests ages ago…

If so, I could go back and turn it off, and that would stop me getting double emails for CI failures…

**Comment by bergjohan** [comment]
Ok, I see.. yes, you should be able to disable it. This is what it looked like for me:

test

**Comment by claremacrae** [comment]
Oh that’s really interesting… I wonder what it is about this action… It might be that the only triggers are for PRs and cron, if I read that correctly…

So I’ll go ahead and accept the PR - and then afterwards, update my fork of this repo, and undoubtedly confirm that I see the same behaviour…

If we can find out what it is about the action that causes that banner to show, maybe as a later step we could add a comment in it, to try to keep it that way…

**Pull request merged**
